### ISSUE TITLE
Searching for "firewall" in Wingpanel doesn't yield result

### ISSUE THREAD

**Issue by jtrees** [elementary/switchboard-plug-security-privacy#30]
### Steps to Reproduce
1. Open the Applications menu
2. Type "firewall"

### Expected Result
The "Security & Privacy" plug should turn up as a result.

### Actual Result
No search results.

**Comment by davidmhewitt** [comment]
Closing this for `switchboard-plug-security-privacy` and opening in `applications-menu` instead. Searching for "firewall" within switchboard does indeed yield the correct plug, so there's no problems in this codebase. It would seem that the applications menu has only been coded to search on the title of plugs rather than use the search functionality within switchboard:

https://github.com/elementary/applications-menu/blob/master/lib/synapse-plugins/switchboard-plugin.vala#L140

New bug opened here: https://github.com/elementary/applications-menu/issues/49
