### ISSUE TITLE
Location service notworking

### ISSUE THREAD

**Issue by torikulhabib** [elementary/switchboard-plug-security-privacy#64]
Location service not working.
i turn off location but app still share location.
![switchboard privacy](https://user-images.githubusercontent.com/26135527/49798407-c486c380-fd74-11e8-988e-b78253a01973.png)

**Comment by J0Ar** [comment]
I noticed this because Nightlight uses location service too for correct sunset/sunrise setting...by default location service is off i think. (in dconf-settings)
I tried to enable location services in security-privacy-plug, but that doesnt work.
I only got it working with dconf-editor, or in terminal...

_gsettings get org.gnome.system.location enabled  #shows the current value
gsettings set org.gnome.system.location enabled true  #location service on
gsettings set org.gnome.system.location enabled false #location service off_

**Comment by J0Ar** [comment]
On elementaryOS 5.1 Hera liveCD the key `gsettings get org.gnome.system.location enabled` is disabled by default and the setting in switchboad-plug-security-privacy has no effect.
So the system can't update to the correct timezone automatically. 
By pasting the key `gsettings set org.gnome.system.location enabled true` in terminal the time updates immediately.

**Comment by jhorgint** [comment]
I run 'gsettings set org.gnome.system.location enabled true'
  but i got this error message
     dconf-WARNING **: 19:25:32.011: failed to commit changes to dconf: Cannot autolaunch D-Bus without X11 $DISPLAY

I'm using ubuntu on WSL2

**Comment by danirabbit** [comment]
Gonna close this since we're migrated to the location portal since this was filed so there's a whole different system for location services
